variable "vpc-name" {}
variable "vpc_cidr" {}
variable "pub-sub-cidr" {}
variable "pri-sub-cidr" {}
variable "ami" {}
variable "instance-type" {}
variable "region" {}
variable "pub-sub-az" {}
variable "pri-sub-az" {}
variable "key-name" {}
